int absolute(int n);
char *cap_string(char *c);
char *concat_strings(char *dest, const char *src);
int first_digit(int n);
int is_prime_number(int n);
char lowercase(char c);
char *nconcat_strings(char *dest, const char *src, int n);
void positive_or_not(int n);
int power(int x, int y);
void print_array(int *a, int n);
void print_number(int n);
void print_string(char *str);
void reverse_array(int *a, int n);
void reverse_string(char *s);
int square_root(int n);
int str_len(char *s);
char *string_copy(char *dest, const char *src);
char *string_ncopy(char *dest, const char *src, int n);
int string_to_integer(char *s);
int strings_compare(char *s1, const char *s2);
void swap_int(int *a, int *b);
char *uppercase_string(char *c);
char uppercase(char c);
int print_char(char c);
